### ISSUE TITLE
Actions: add github actions to build and deploy the web app to Github Pages

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/reactgeoda#13]
See https://github.com/gregrickaby/nextjs-github-pages for example

**Comment by justin-kleid** [comment]
Hi, I noticed there were some needed action configurations for the repo's settings. Not sure if that has already been set up, but I do not have access to the settings

**Comment by lixun910** [comment]
https://geodacenter.github.io/reactgeoda/
