### ISSUE TITLE
add an option to terminate an OpenAI query

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/reactgeoda#133]
Is there a way to add an option to terminate a query? E.g., I asked these two questions that for some reason resulted in a loop (no answer) but there wasn't an obvious way to get out.
<img width="380" alt="Screenshot 2024-06-24 at 11 56 35 AM" src="https://github.com/GeoDaCenter/reactgeoda/assets/13679743/521d91d5-0684-4728-a780-ea4b6842e01e">

**Comment by lixun910** [comment]
Fix this in: https://draft-142--geodaai.netlify.app/mapland

Added a stop button to allow terminating the conversation (or hanging response), and a report button to allow user to send an email to us for help:
<img width="359" alt="Screenshot 2024-06-27 at 4 50 46 PM" src="https://github.com/GeoDaCenter/reactgeoda/assets/2423887/abd80bcc-4118-4f5b-b64c-90941ec1212c">
