### ISSUE TITLE
crash when trying to create a unique values map for a continuous variable

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/reactgeoda#139]
I asked geoda.ai to list the available map types for UE90. It responded with the list of all map types, incl. unique values.

When I then asked it to create a unique values map for UE90 (a continuous variable), it crashed. 

Can we restrict the list of suggested map types to the variable type (e.g. no unique values map for continuous variables etc.)?

**Comment by lixun910** [comment]
Fixed
