### ISSUE TITLE
Github actions workflow

### ISSUE THREAD

**Issue by justin-kleid** [GeoDaCenter/reactgeoda#25]
When I squash and merge a pull request to the main branch, the actual event pushes code to the branch. In the nextjs.yml file, we have -- if: github.event.pull_request.merged == true -- which is thus ignored for squash merge. Should we change the condition to include push events, or just not use squash and merge

**Comment by lixun910** [comment]
Addressed by PR #27 and PR #26  PR #24 
See: https://geodacenter.github.io/reactgeoda/
